-- NOTE: All config is in mason.lua

-- require("lspconfig").dartls.setup({
-- 	cmd = { "dart", "language-server", "--protocol=lsp" },
-- 	-- 	lsp = {
-- 	-- 		color = { -- show the derived colours for dart variables
-- 	-- 			enabled = true, -- whether or not to highlight color variables at all, only supported on flutter >= 2.10
-- 	-- 			background = true, -- highlight the background
-- 	-- 			background_color = nil, -- required, when background is transparent (i.e. background_color = { r = 19, g = 17, b = 24},)
-- 	-- 			foreground = true, -- highlight the foreground
-- 	-- 			virtual_text = true, -- show the highlight using virtual text
-- 	-- 			virtual_text_str = "■", -- the virtual text character to highlight
-- 	-- 		},
-- 	-- 		settings = {
-- 	-- 			enableSnippets = true,
-- 	-- 			updateImportsOnRename = true, -- Whether to update imports and other directives when files are renamed. Required for `FlutterRename` command.
-- 	-- 		},
-- 	-- 	},
-- })

-- require("flutter-tools").setup({
-- 	lsp = {
-- 		-- color = { -- show the derived colours for dart variables
-- 		-- 	enabled = true, -- whether or not to highlight color variables at all, only supported on flutter >= 2.10
-- 		-- 	background = true, -- highlight the background
-- 		-- 	background_color = nil, -- required, when background is transparent (i.e. background_color = { r = 19, g = 17, b = 24},)
-- 		-- 	foreground = false, -- highlight the foreground
-- 		-- 	virtual_text = true, -- show the highlight using virtual text
-- 		-- 	virtual_text_str = "■", -- the virtual text character to highlight
-- 		-- },
--
-- 		statusline = {
-- 			-- set to true to be able use the 'flutter_tools_decorations.app_version' in your statusline
-- 			-- this will show the current version of the flutter app from the pubspec.yaml file
-- 			app_version = true,
-- 			-- set to true to be able use the 'flutter_tools_decorations.device' in your statusline
-- 			-- this will show the currently running device if an application was started with a specific
-- 			-- device
-- 			device = true,
-- 			-- set to true to be able use the 'flutter_tools_decorations.project_config' in your statusline
-- 			-- this will show the currently selected project configuration
-- 			project_config = false,
-- 		},
-- 		get_guides = {
-- 			enabled = false,
-- 		},
--
-- 		closing_tags = {
-- 			highlight = "ErrorMsg", -- highlight for the closing tag
-- 			prefix = ">", -- character to use for close tag e.g. > Widget
-- 			priority = 10, -- priority of virtual text in current line
-- 			-- consider to configure this when there is a possibility of multiple virtual text items in one line
-- 			-- see `priority` option in |:help nvim_buf_set_extmark| for more info
-- 			enabled = true, -- set to false to disable
-- 		},
--
-- 		settings = {
-- 			enableSnippets = true,
-- 			updateImportsOnRename = true, -- Whether to update imports and other directives when files are renamed. Required for `FlutterRename` command.
-- 		},
-- 	},
-- }) -- use defaults
